name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2
      - name: Setup node.js 19
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Run lint
        run: pnpm run lint
